spring.application.name=backend
server.port=${PORT:8080}

# 1. URL de conexión (asegúrate de que la BD 'colegio' esté creada en pgAdmin)
spring.datasource.url=jdbc:postgresql://localhost:5432/colegio

# 2. Usuario por defecto de PostgreSQL (suele ser 'postgres')
spring.datasource.username=postgres

# 3. Pon aquí la contraseña REAL que configuraste al instalar PostgreSQL
spring.datasource.password=admin

# 4. El driver que acabamos de reparar
spring.datasource.driver-class-name=org.postgresql.Driver

# 5. Propiedades de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect